### ISSUE TITLE
Localization, internationalization and meta (SEO)

### ISSUE THREAD

**Issue by Cyberuben** [basement-js/basement#4]
Localization and internationalization should be supported by default.

The ability to serve your entire website in a different language, where possible, automatically.
#### Reference
- https://support.google.com/webmasters/answer/189077
- https://support.google.com/webmasters/answer/182192?hl=en#1
- http://static.googleusercontent.com/media/www.google.com/nl//webmasters/docs/search-engine-optimization-starter-guide.pdf
#### Tasks
- [ ] Load language strings from file, not hard-coded in the template (provide API endpoint to retrieve values)
- [ ] Load numbers from API into local standard
- [ ] Default language (every page should have at least this language available)
- [ ] Load localized or internationalized data from the database
- [ ] Provide URLs to for all available language for a certain page (`<link rel="alternate" href="http://example.com/nl" hreflang="nl" />`)
- [ ] Get meta description / meta keywords from API
- [ ] Detect default language from `Accept-Language` HTTP header (GeoIP fallback) when no language is specified in URL
